apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    node.type: es-node-master
  name: es
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      node.type: es-node-master
  template:
    metadata:
      labels:
        node.type: es-node-master
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: es-node-master-container
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            exec:
              command:
              - curl
              - localhost:9200/_cluster/health
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - curl
              - localhost:9200/_cluster/health
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 9200
            - containerPort: 9300
          volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    es.service: es-service
  name: es-service
  namespace: logging
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    node.type: es-node-master

